DROP TABLE IF EXISTS favorites CASCADE;

CREATE TABLE favorites (
  id SERIAL PRIMARY KEY NOT NULL,
  song VARCHAR(25) NOT NULL,
  artist VARCHAR(25) NOT NULL,
  album VARCHAR(25) NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE);
